### ISSUE TITLE
Build for System.Windows.Forms fails in Ubuntu

### ISSUE THREAD

**Issue by areller** [dotnet/winforms#2636]
* .NET Core Version: 3.1.100
* Have you experienced this same bug with .NET Framework?: No (Didn't try, running on Ubuntu)

**Problem description:**
I run Ubuntu18.04.3 with .NET Core 3.1.100.
I use the `release/3.1` branch
When I try to run `dotnet build` from the `src/System.Windows.Forms/src` directory, it fails with this message,  

```
CSC : error CS1566: Error reading resource 'System.Windows.Forms.Arrow' -- 'Could not find file '/home/areller/playground/winforms/src/System.Windows.Forms/src/Resources/System/Windows/Forms/PropertyGrid/Arrow.ico'.' [/home/areller/playground/winforms/src/System.Windows.Forms/src/System.Windows.Forms.csproj]
```

![image](https://user-images.githubusercontent.com/15989650/71786717-582dd080-3017-11ea-823a-0efcdf5d339c.png)

**Actual behavior:** `dotnet build` fails (see above)   
It seems that it can't find some resource (`Arrow.ico`), but this resource exists when I open it directly, and the build works on other systems (Windows and macOS).

**Expected behavior:** `dotnet build` should work  
This is a screenshot of it working on macOS 10.14.6

![image](https://user-images.githubusercontent.com/15989650/71786735-a8a52e00-3017-11ea-9f7d-a8c11f244961.png)

I know that _winforms_ doesn't support Linux/macOS, but I want to experiment with it so I need it to build.

**Comment by RussKie** [comment]
I think it breaks because of the casing, the file is in the lower case:
https://github.com/dotnet/winforms/tree/release/3.1/src/System.Windows.Forms/src/Resources/System/Windows/Forms/PropertyGrid

I'm not sure why it is working on the MacOS though...

**Comment by areller** [comment]
@RussKie Right! I missed it
I see that there are a lot of other inconsistencies in the casing of resources. I'll fix them and update if the problem still occurs. Thank you.

As for why it works on macOS, I think that APFS is by default case-insensitive - https://support.apple.com/guide/disk-utility/file-system-formats-available-in-disk-utility-dsku19ed921c/18.0/mac/10.14

**Comment by RussKie** [comment]
> I'll fix them and update if the problem still occurs. Thank you.

👍 
We accept PRs as well 😉

**Comment by areller** [comment]
@RussKie The build works now, after I've fixed the resources files casing.
I'll publish a PR tomorrow.
Thank you for your help.

**Comment by merriemcgaw** [comment]
@RussKie / @areller is this issue ready to be closed then?

**Comment by RussKie** [comment]
Yes, thank you for the heads up.
