### ISSUE TITLE
IDE0036 errors when building with Preview 6 SDK

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/winforms#11493]
When building with .NET 9 Preview 6 SDK (i.e. 9.0.100-preview.6.24303.27), there are 3 IDE0036 errors:
```
    D:\a\_work\1\vmr\src\winforms\src\System.Drawing.Common\src\System\Drawing\ImageConverter.cs(42,5): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [D:\a\_work\1\vmr\src\winforms\src\System.Drawing.Common\src\System.Drawing.Common.csproj::TargetFramework=net8.0]
    D:\a\_work\1\vmr\src\winforms\src\System.Drawing.Common\src\System\Drawing\ImageConverter.cs(42,5): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [D:\a\_work\1\vmr\src\winforms\src\System.Drawing.Common\src\System.Drawing.Common.csproj::TargetFramework=net9.0]
    D:\a\_work\1\vmr\src\winforms\src\System.Drawing.Common\src\System\Drawing\Imaging\Effects\Effect.cs(11,1): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [D:\a\_work\1\vmr\src\winforms\src\System.Drawing.Common\src\System.Drawing.Common.csproj::TargetFramework=net9.0]
```

From: https://github.com/dotnet/sdk/pull/41417#issuecomment-2150906686

**Comment by elachlan** [comment]
We have it set to a warning in the CodeAnalysis globalconfig. Maybe it isn't getting applied to `System.Drawing.Common`?
https://github.com/dotnet/winforms/blob/aa6177871546030140d82c1e0ebcf80f9291e0d9/eng/CodeAnalysis.src.globalconfig#L1541-L1542

**Comment by NikolaMilosavljevic** [comment]
Source-build and unified-build use `/p:TreatWarningsAsErrors=true` so all warnings will become errors.

There are more errors, of the same type: https://github.com/dotnet/sdk/pull/41417#issuecomment-2151382065

**Comment by elachlan** [comment]
We have `TreatWarningsAsErrors=true` in our CI builds. I also locally set the analyzer to error instead of warning and didn't get any hits. Its like the analyzer isn't getting run.

**Comment by elachlan** [comment]
@sharwell `IDE0036` seems to not be working here, could you point us in the right direction?

**Comment by akoeplinger** [comment]
Maybe caused by https://github.com/dotnet/roslyn/pull/73339? i.e. it was silently ignored before that fix

**Comment by ViktorHofer** [comment]
Any update on this? We still have a patch for it in the VMR: https://github.com/dotnet/sdk/blob/main/src/SourceBuild/patches/winforms/0001-Suppress-IDE0036-errors.patch

**Comment by elachlan** [comment]
@ViktorHofer we think it's a Roslyn bug? The analyzer isn't firing for us.

**Comment by akoeplinger** [comment]
@elachlan I hacked the System.Drawing.Common build so it still built with the 8.0.100 SDK and it does show the same analyzer errors there so I'm almost certain that it was just silently ignored on 8.0.200+ until the fix in https://github.com/dotnet/roslyn/pull/73339

So these look like genuine findings. You can bump the SDK version to e.g. `9.0.100-preview.6.24303.27` in global.json locally and run build.cmd, it will show the errors.

**Comment by akoeplinger** [comment]
Opened a PR: https://github.com/dotnet/winforms/pull/11571
