### ISSUE TITLE
SetWindowsHookEx API is not working for mouse actions in .NET7.0

### ISSUE THREAD

**Issue by GokulThanu** [dotnet/winforms#10173]
### .NET version

.net7.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

It works in .net6.0 and earlier versions

### Issue description

The mouse action is not captured by the SetWindowsHookEx API in .Net7.0 which works in the earlier version.

I have already created an issue regarding this but the solution given is not working in framework 4.8 versions. It shows the error" Native sized interger is not available in c#". Please find the old issue link

https://github.com/dotnet/winforms/issues/9535.

### Steps to reproduce

Sample

[WindowsFormsApp1.zip](https://github.com/dotnet/winforms/files/13066117/WindowsFormsApp1.zip)

- Run the sample 
- Note that the compilation error occurs

**Comment by elachlan** [comment]
> [C# 9](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9) is supported only on .NET 5 and newer versions.

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

**Comment by elachlan** [comment]
@GokulThanu the error is because of the C# Version. You might need to use `IntPtr` and Preprocessor Directives (to have different code for framework vs Net5+) https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives to avoid the issue.
